### ISSUE TITLE
LOW_NTC_TEMP false positive

### ISSUE THREAD

**Issue by edoardo-conti** [SimosMCmuffin/FlexiBMS_Lite_FW#8]
If you set the _Par. #13_ (fw: 0.17c) for the lowest allowed external NTC-temperature of the battery it always triggers "LOW_NTC_TEMP" fault and halts charging.

In my case I set `$13=278` (~ 5°C) and from the reading I got values around 290 (NTC-TEMPERATURE PROBE, 10KOHM).
It triggers the fault with no reason: 278<290 .

I have tried different values but the result is always the same.

**Comment by SimosMCmuffin** [comment]
Can you paste all the values of the parameters you're using at the moment?

What does the NTC-probe report at room temperature? EDIT: 290?, sounds normal.
https://github.com/SimosMCmuffin/FlexiBMS_Lite_FW/wiki/State-printout-breakdown

I'm guessing the low NTC temp fault gets triggered immediately when charging is starting?

**Comment by SimosMCmuffin** [comment]
Found the problem.

https://github.com/SimosMCmuffin/FlexiBMS_Lite_FW/blob/bfdcf9379b43f339a6dee42017856a2b3c8e77a9/Src/AuxFunctions.c#L998-L1022

There is a typo, that causes the measured NTC temperature to be compared against $7 (minPackVolt) and $8 (maxPackVolt), instead of the $13 (minNTCtemp) and $14 (maxNTCtemp) respectively.

**Recommended quick fix for the moment:** 
Set parameters $7 and $8 to have same values as $13 and $14 ($7=$13 and $8=$14). If you're using cell sensing ($0, packCellCount is not 0), then this shouldn't affect anything else, as the pack voltages are not used if cell sensing is used

I'll add this fix to the 0.18.

Report back if this fixed the issue and thanks for informing about it!

**Comment by edoardo-conti** [comment]
Sure. Unfortunately at the moment I don't have access to the BMS's usb port, so I read / write through the metr app:
<details>
  <summary>Screenshot</summary>
  <img src="https://user-images.githubusercontent.com/10279685/110339965-06bd0f00-8029-11eb-816a-1c5e769fe6cb.JPEG" width="200" >
</details>

> I'm guessing the low NTC temp fault gets triggered immediately when charging is starting? 

You're right. 

> Found the problem.
> [...]
> There is a typo, that causes the measured NTC temperature to be compared against $7 (minPackVolt) and $8 (maxPackVolt), instead of the $13 (minNTCtemp) and $14 (maxNTCtemp) respectively.

Oh, I had already checked that source file quickly and hadn't noticed it! 

> I'll add this fix to the 0.18.

Perfect, thanks!

------

> **Recommended quick fix for the moment:**
> Set parameters $7 and $8 to have same values as $13 and $14 ($7=$13 and $8=$14). If you're using cell sensing ($0, packCellCount is not 0), then this shouldn't affect anything else, as the pack voltages are not used if cell sensing is used

Just tested, I can confirm that this quick fix solve the problem.

**Comment by SimosMCmuffin** [comment]
Fix will be rolled out in 0.18
